imports:
    - "statementDefinition.yml"

parameters:
    dbDriver: "mysql"
    dbHost: ""
    dbUsername: ""
    dbPassword: ""
    dbName: ""

    defaultDsn: "{dbDriver}:dbname={dbName};host={dbHost}"
    dsnTemplate: "%defaultDsn%"

    identifierDelimiter: "`"

    useMysqlBufferedQueries: false

    silktide_reposition::tokenDefinitions: "%sqlStatementDefinition%"

services:
    storage:
        class: Silktide\Reposition\Sql\Storage\SqlStorage
        arguments:
            - "@dbAdapter"
            - "@interpreter"
            - "@silktide_reposition::defaultHydrator"
            - "@normaliser"

    dbAdapter:
        class: Silktide\Reposition\Sql\Storage\PdoAdapter
        arguments:
            - "@credentials"
            - "%dsnTemplate%"
            - true
            - "%useMysqlBufferedQueries%"

    credentials:
        class: Silktide\Reposition\Sql\Storage\DbCredentials
        arguments:
            - "%dbDriver%"
            - "%dbHost%"
            - "%dbUsername%"
            - "%dbPassword%"
            - "%dbName%"

    interpreter:
        class: Silktide\Reposition\Sql\QueryInterpreter\SqlQueryInterpreter
        arguments:
            - "@silktide_reposition::tokenParser"
            - "#queryTypeInterpreter"
            - "%identifierDelimiter%"

    findInterpreter:
        class: Silktide\Reposition\Sql\QueryInterpreter\Type\FindInterpreter
        tags:
            - "queryTypeInterpreter"

    saveInterpreter:
        class: Silktide\Reposition\Sql\QueryInterpreter\Type\SaveInterpreter
        tags:
            - "queryTypeInterpreter"

    updateInterpreter:
        class: Silktide\Reposition\Sql\QueryInterpreter\Type\UpdateInterpreter
        tags:
            - "queryTypeInterpreter"

    deleteInterpreter:
        class: Silktide\Reposition\Sql\QueryInterpreter\Type\DeleteInterpreter
        tags:
            - "queryTypeInterpreter"

    normaliser:
        class: Silktide\Reposition\Sql\Normaliser\SqlNormaliser

    silktide_reposition::defaultStorage:
        aliasOf: "@storage"

    silktide_reposition::defaultNormaliser:
        aliasOf: "@normaliser"